from .route_arquivos import arquivos_bp
from .route_usuarios import usuarios_bp
from .route_vinculos import vinculos_bp
from .route_turmas import turmas_bp
from .route_materias import materias_bp
from .route_chats import chats_bp
from .route_mensagens import mensagens_bp
from .route_data import data_bp
from .route_admin import admin_bp
from .route_llm import llm_bp