from .model_aluno import Aluno
from .model_professor import Professor
from .model_turma import Turma
from .model_materia import Materia
from .model_documento import Documento
from .model_aluno_turma import AlunoTurma
from .model_turma_materia import TurmaMateria
from .model_professor_materia import ProfessorMateria
from .model_documento_materia import DocumentoMateria
