"""Corrigindo quantidade de caracteres das colunas 'semestre' e 'turno' no modelo de Turma

Revision ID: 1122dc4b8c6e
Revises: 1901488fff41
Create Date: 2025-04-18 18:35:09.457284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1122dc4b8c6e'
down_revision = '1901488fff41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.alter_column('semestre',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('turno',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.alter_column('turno',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.alter_column('semestre',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
