"""Definindo algumas colunas de 'Aluno', 'Professor', 'Turma' e 'Materia' como índices

Revision ID: 1901488fff41
Revises: ac2758145d77
Create Date: 2025-04-16 19:05:13.462191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1901488fff41'
down_revision = 'ac2758145d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_constraint('alunos_cpf_key', type_='unique')
        batch_op.drop_constraint('alunos_matricula_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_alunos_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_matricula'), ['matricula'], unique=True)

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint('materias_codigo_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_materias_codigo'), ['codigo'], unique=True)

    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_constraint('professores_cpf_key', type_='unique')
        batch_op.drop_constraint('professores_matricula_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_professores_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_matricula'), ['matricula'], unique=True)

    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_codigo'))

    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professores_matricula'))
        batch_op.drop_index(batch_op.f('ix_professores_email'))
        batch_op.drop_index(batch_op.f('ix_professores_cpf'))
        batch_op.create_unique_constraint('professores_matricula_key', ['matricula'])
        batch_op.create_unique_constraint('professores_cpf_key', ['cpf'])

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materias_codigo'))
        batch_op.create_unique_constraint('materias_codigo_key', ['codigo'])

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_matricula'))
        batch_op.drop_index(batch_op.f('ix_alunos_email'))
        batch_op.drop_index(batch_op.f('ix_alunos_cpf'))
        batch_op.create_unique_constraint('alunos_matricula_key', ['matricula'])
        batch_op.create_unique_constraint('alunos_cpf_key', ['cpf'])

    # ### end Alembic commands ###
