"""Criando nova migração para incluir as novas entidades 'Turma' e 'TurmaMateria' e adaptar outras tabelas para interagir com elas

Revision ID: 2085eb946509
Revises: 41147825ac06
Create Date: 2025-04-08 19:38:04.435104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2085eb946509'
down_revision = '41147825ac06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('semestre', sa.String(length=8), nullable=False),
    sa.Column('turno', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos_turmas',
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'turma_id')
    )
    op.create_table('turmas_materias',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'materia_id')
    )
    op.drop_table('alunos_materias')
    with op.batch_alter_table('documentos_materias', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('professores_materias', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores_materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))

    with op.batch_alter_table('documentos_materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))

    op.create_table('alunos_materias',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('aluno_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('materia_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name='alunos_materias_aluno_id_fkey'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='alunos_materias_materia_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alunos_materias_pkey')
    )
    op.drop_table('turmas_materias')
    op.drop_table('alunos_turmas')
    op.drop_table('turmas')
    # ### end Alembic commands ###
