"""Initial migration.

Revision ID: 41147825ac06
Revises: 
Create Date: 2025-04-01 23:45:16.285902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41147825ac06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_constraint('alunos_email_key', type_='unique')

    with op.batch_alter_table('alunos_materias', schema=None) as batch_op:
        batch_op.drop_constraint('alunos_materias_aluno_id_materia_id_key', type_='unique')
        batch_op.drop_constraint('alunos_materias_aluno_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('alunos_materias_materia_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'])
        batch_op.create_foreign_key(None, 'alunos', ['aluno_id'], ['id'])

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('documentos_professor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'professores', ['professor_id'], ['id'])

    with op.batch_alter_table('documentos_materias', schema=None) as batch_op:
        batch_op.drop_constraint('documentos_materias_documento_id_materia_id_key', type_='unique')
        batch_op.drop_constraint('documentos_materias_documento_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('documentos_materias_materia_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'])
        batch_op.create_foreign_key(None, 'documentos', ['documento_id'], ['id'])

    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricula', sa.String(length=100), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_constraint('professores_email_key', type_='unique')
        batch_op.drop_constraint('professores_num_cadastro_key', type_='unique')
        batch_op.create_unique_constraint(None, ['matricula'])
        batch_op.drop_column('num_cadastro')

    with op.batch_alter_table('professores_materias', schema=None) as batch_op:
        batch_op.drop_constraint('professores_materias_professor_id_materia_id_key', type_='unique')
        batch_op.drop_constraint('professores_materias_materia_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('professores_materias_professor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'])
        batch_op.create_foreign_key(None, 'professores', ['professor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores_materias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('professores_materias_professor_id_fkey', 'professores', ['professor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('professores_materias_materia_id_fkey', 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('professores_materias_professor_id_materia_id_key', ['professor_id', 'materia_id'])

    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_cadastro', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('professores_num_cadastro_key', ['num_cadastro'])
        batch_op.create_unique_constraint('professores_email_key', ['email'])
        batch_op.alter_column('senha',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=48),
               existing_nullable=False)
        batch_op.drop_column('matricula')

    with op.batch_alter_table('documentos_materias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('documentos_materias_materia_id_fkey', 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('documentos_materias_documento_id_fkey', 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('documentos_materias_documento_id_materia_id_key', ['documento_id', 'materia_id'])

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('documentos_professor_id_fkey', 'professores', ['professor_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('alunos_materias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('alunos_materias_materia_id_fkey', 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('alunos_materias_aluno_id_fkey', 'alunos', ['aluno_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('alunos_materias_aluno_id_materia_id_key', ['aluno_id', 'materia_id'])

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_unique_constraint('alunos_email_key', ['email'])
        batch_op.alter_column('senha',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=48),
               existing_nullable=False)
        batch_op.alter_column('matricula',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
