"""Initial migration

Revision ID: 4259142b04a7
Revises: 
Create Date: 2025-05-08 18:21:03.948557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4259142b04a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('senha', sa.String(length=32), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_matricula'), ['matricula'], unique=True)

    op.create_table('materias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materias_codigo'), ['codigo'], unique=True)

    op.create_table('professores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('senha', sa.String(length=32), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professores_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_matricula'), ['matricula'], unique=True)

    op.create_table('turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('semestre', sa.String(length=6), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_codigo'), ['codigo'], unique=True)

    op.create_table('alunos_turmas',
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'turma_id')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores_turmas_materias',
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'turma_id', 'materia_id')
    )
    op.create_table('turmas_materias',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'materia_id')
    )
    op.create_table('arquivos_turmas_materias',
    sa.Column('arquivo_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('arquivo_id', 'turma_id', 'materia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arquivos_turmas_materias')
    op.drop_table('turmas_materias')
    op.drop_table('professores_turmas_materias')
    op.drop_table('arquivos')
    op.drop_table('alunos_turmas')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_codigo'))

    op.drop_table('turmas')
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professores_matricula'))
        batch_op.drop_index(batch_op.f('ix_professores_email'))
        batch_op.drop_index(batch_op.f('ix_professores_cpf'))

    op.drop_table('professores')
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materias_codigo'))

    op.drop_table('materias')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_matricula'))
        batch_op.drop_index(batch_op.f('ix_alunos_email'))
        batch_op.drop_index(batch_op.f('ix_alunos_cpf'))

    op.drop_table('alunos')
    # ### end Alembic commands ###
