"""Refatorando

Revision ID: 42a84264a154
Revises: b0443e2531fa
Create Date: 2025-12-10 23:43:46.243803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a84264a154'
down_revision = 'b0443e2531fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROFESSOR', 'ALUNO', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_matricula'), ['matricula'], unique=True)

    op.create_table('sessao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dono_id', sa.UUID(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['dono_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_cpf'))
        batch_op.drop_index(batch_op.f('ix_alunos_email'))
        batch_op.drop_index(batch_op.f('ix_alunos_matricula'))

    op.drop_table('alunos')
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professores_cpf'))
        batch_op.drop_index(batch_op.f('ix_professores_email'))
        batch_op.drop_index(batch_op.f('ix_professores_matricula'))

    op.drop_table('professores')
    with op.batch_alter_table('alunos_turmas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alunos_turmas_aluno_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['aluno_id'], ['id'])

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('arquivos_professor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['professor_id'], ['id'])

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materia_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('chats_aluno_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['aluno_id'], ['id'])
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'])

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sessao_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('mensagens_chat_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessao', ['sessao_id'], ['id'])
        batch_op.drop_column('chat_id')

    with op.batch_alter_table('professores_turmas_materias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('professores_turmas_materias_professor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['professor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores_turmas_materias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('professores_turmas_materias_professor_id_fkey'), 'professores', ['professor_id'], ['id'])

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mensagens_chat_id_fkey'), 'chats', ['chat_id'], ['id'])
        batch_op.drop_column('sessao_id')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chats_aluno_id_fkey'), 'alunos', ['aluno_id'], ['id'])
        batch_op.drop_column('materia_id')

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('arquivos_professor_id_fkey'), 'professores', ['professor_id'], ['id'])

    with op.batch_alter_table('alunos_turmas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alunos_turmas_aluno_id_fkey'), 'alunos', ['aluno_id'], ['id'])

    op.create_table('professores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('professores_pkey'))
    )
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professores_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_cpf'), ['cpf'], unique=True)

    op.create_table('alunos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('alunos_pkey'))
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_cpf'), ['cpf'], unique=True)

    op.drop_table('sessao')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_matricula'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
