"""Corrige relacionamentos e FKs dos models

Revision ID: 54bc685a0304
Revises: 
Create Date: 2025-12-13 01:45:09.694392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bc685a0304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materias_codigo'), ['codigo'], unique=True)

    op.create_table('turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('semestre', sa.String(length=6), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_codigo'), ['codigo'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROFESSOR', 'ALUNO', name='roleenum', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_matricula'), ['matricula'], unique=True)

    op.create_table('alunos_turmas',
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'turma_id')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores_turmas_materias',
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'turma_id', 'materia_id')
    )
    op.create_table('sessao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dono_id', sa.UUID(), nullable=False),
    sa.Column('inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fim', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dono_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas_materias',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'materia_id')
    )
    op.create_table('arquivos_turmas_materias',
    sa.Column('arquivo_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('arquivo_id', 'turma_id', 'materia_id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('conteudo', sa.String(length=3200), nullable=False),
    sa.Column('data_envio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens')
    op.drop_table('arquivos_turmas_materias')
    op.drop_table('turmas_materias')
    op.drop_table('sessao')
    op.drop_table('professores_turmas_materias')
    op.drop_table('chats')
    op.drop_table('arquivos')
    op.drop_table('alunos_turmas')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_matricula'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_codigo'))

    op.drop_table('turmas')
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materias_codigo'))

    op.drop_table('materias')
    # ### end Alembic commands ###
