"""criar tabela llm e fk em materias

Revision ID: 7487a1a7e894
Revises: ca3358ed84ce
Create Date: 2026-04-01 17:36:10.193313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7487a1a7e894'
down_revision = 'ca3358ed84ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_materias_llm_id', 'llm', ['llm_id'], ['model_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_materias_llm_id', type_='foreignkey')
        batch_op.drop_column('llm_id')

    op.drop_table('llm')
    # ### end Alembic commands ###
