"""Criando novos modelos de Chat e Mensagem; Atualizando o tamanho do campo 'senha' nos modelos de Aluno e Professor

Revision ID: 96838b04f39b
Revises: 4259142b04a7
Create Date: 2025-06-03 18:45:00.339745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96838b04f39b'
down_revision = '4259142b04a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('conteudo', sa.String(length=3200), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    op.drop_table('mensagens')
    op.drop_table('chats')
    # ### end Alembic commands ###
