"""Alterando o campo 'sender_id' do modelo de Mensagem para não referenciar a tabela 'alunos'

Revision ID: b0443e2531fa
Revises: 96838b04f39b
Create Date: 2025-06-04 00:27:09.394896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0443e2531fa'
down_revision = '96838b04f39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_constraint('mensagens_sender_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.create_foreign_key('mensagens_sender_id_fkey', 'alunos', ['sender_id'], ['id'])

    # ### end Alembic commands ###
