"""Removendo os modelos intermediários 'ProfessorTurma' e 'ProfessorMateria' e criando 'ProfessorTurmaMateria'

Revision ID: b86f832bea42
Revises: 1122dc4b8c6e
Create Date: 2025-04-30 20:15:25.198881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86f832bea42'
down_revision = '1122dc4b8c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professores_turmas_materias',
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'turma_id', 'materia_id')
    )
    op.drop_table('professores_turmas')
    op.drop_table('professores_materias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professores_materias',
    sa.Column('professor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('materia_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='professores_materias_materia_id_fkey'),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], name='professores_materias_professor_id_fkey')
    )
    op.create_table('professores_turmas',
    sa.Column('professor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('turma_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], name='professores_turmas_professor_id_fkey'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name='professores_turmas_turma_id_fkey'),
    sa.PrimaryKeyConstraint('professor_id', 'turma_id', name='professores_turmas_pkey')
    )
    op.drop_table('professores_turmas_materias')
    # ### end Alembic commands ###
