"""altera campo usuario

Revision ID: c8ef4570badd
Revises: 7487a1a7e894
Create Date: 2026-05-09 03:34:57.396474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ef4570badd'
down_revision = '7487a1a7e894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(length=8), nullable=False))
        batch_op.alter_column('sender_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###
