"""retirando obrigatoriedade do sessaoid

Revision ID: ca3358ed84ce
Revises: 54bc685a0304
Create Date: 2025-12-13 04:23:15.774373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3358ed84ce'
down_revision = '54bc685a0304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.alter_column('sessao_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.alter_column('sessao_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
