"""aumenta campo senha para 256

Revision ID: f84352a987bc
Revises: ed8be2427b8b
Create Date: 2026-05-12 22:08:20.579788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84352a987bc'
down_revision = 'ed8be2427b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ADMIN', 'PROFESSOR', 'ALUNO', 'ATIVO', 'INATIVO', name='roleenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ATIVO'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ADMIN', 'PROFESSOR', 'ALUNO', 'ATIVO', 'INATIVO', name='roleenum', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'ATIVO'::character varying"))
        batch_op.alter_column('senha',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
